global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: mssql-exporter-exporter
    static_configs:
      - targets: ["mssql-exporter:4000"]
  # - job_name: edgesql-exporter-exporter
  #   static_configs:
  #     - targets: ["edgesql_exporter:9237"]
